-- AXON S4 Merged — Capability Registry Seed
-- Target location: schema/seeds/001_capability_registry.sql
--
-- Purpose:
--   Formalise the S2 capability_registry seed data in a dedicated seed file.
--
-- Relationship to migration:
--   S2 currently also seeds these rows in schema/migrations/001_initial_schema.sql
--   so the capability hard gate is immediately usable after migration.
--   This file does not replace or modify that migration. It is additive and
--   safe to run repeatedly.
--
-- Idempotency:
--   INSERT OR IGNORE is used against the UNIQUE capability_key constraint.
--   This prevents duplicate records on repeated startup/seed execution.
--
-- Tradeoff:
--   INSERT OR IGNORE does not update existing rows if descriptions, rollback
--   notes, or implementation statuses change later. Changes to seeded
--   capability definitions should be handled by a future explicit migration
--   or controlled upsert.
--
-- Safety:
--   Both permitted and explicitly blocked MVP action classes are registered.
--   Unknown or absent capabilities must fail closed in application code.

-- ---------------------------------------------------------------------------
-- Permitted MVP capabilities
-- ---------------------------------------------------------------------------

INSERT OR IGNORE INTO capability_registry (
    capability_id,
    capability_key,
    display_name,
    category,
    description,
    is_permitted_in_mvp,
    blocked_reason,
    risk_level,
    requires_admin,
    required_permissions_json,
    requires_gpu_telemetry,
    requires_thermal_data,
    reversibility_class,
    rollback_description,
    rollback_notes,
    permission_notes,
    safety_notes,
    implementation_status,
    added_in_version,
    created_at,
    updated_at
)
VALUES
(
    'cap_startup_app_toggle',
    'startup_app_toggle',
    'Startup app toggle',
    'startup_management',
    'Enable or disable a non-critical startup application after explicit user approval.',
    1,
    NULL,
    'medium',
    0,
    '["read_startup_entries","write_user_startup_entries"]',
    0,
    0,
    'toggle_reversal',
    'Rollback restores the previous enabled/disabled startup state recorded before the action.',
    'Rollback depends on capturing the exact startup entry location and previous enabled state.',
    'May require user-level or admin access depending on startup location.',
    'MVP must use allowlists/blocklists and avoid security, driver, vendor updater, and unknown critical entries.',
    'planned',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_process_suspend',
    'process_suspend',
    'Process suspension',
    'process_management',
    'Temporarily suspend a curated safe background process after explicit user approval.',
    1,
    NULL,
    'medium',
    0,
    '["enumerate_processes","suspend_process","resume_process"]',
    0,
    0,
    'process_resume',
    'Rollback resumes the suspended process if it still exists and was suspended by Axon.',
    'If the process exits naturally, rollback becomes a no-op rather than a failure.',
    'Some processes may be protected or require elevation.',
    'Never suspend system-critical, security, anti-cheat, game, driver, or unknown processes in MVP.',
    'planned',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_power_profile_change',
    'power_profile_change',
    'Power profile change',
    'power_management',
    'Switch between supported Windows power profiles after explicit user approval.',
    1,
    NULL,
    'medium',
    0,
    '["read_power_profile","set_power_profile"]',
    0,
    0,
    'previous_value_restore',
    'Rollback restores the previous power profile recorded before the action.',
    'Do not create or modify custom power plan internals in MVP.',
    'Power profile commands vary by Windows version and permissions.',
    'Do not create custom power plans or permanently alter hidden power settings in MVP.',
    'planned',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_temporary_optimization_state',
    'temporary_optimization_state',
    'Temporary optimisation state',
    'temporary_state',
    'Apply a temporary Axon-controlled optimisation mode that expires or can be reverted.',
    1,
    NULL,
    'low',
    0,
    '["create_temporary_state","clear_temporary_state"]',
    0,
    0,
    'temporary_expiry',
    'Rollback cancels the temporary state or waits for natural expiry.',
    'Temporary states must have an expiry condition and clear user visibility.',
    'Should not rely on permanent OS configuration changes.',
    'Must be time-bounded and clearly visible to the user.',
    'planned',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_cache_cleanup',
    'cache_cleanup',
    'Cache cleanup',
    'storage_management',
    'Clean selected temporary/cache files after explicit user approval.',
    1,
    NULL,
    'medium',
    0,
    '["scan_temp_locations","delete_selected_cache_files"]',
    0,
    0,
    'natural_rebuild',
    'This is not true restoration: cleared caches are expected to rebuild naturally when applications need them.',
    'Rollback should never claim that deleted cache files are restored from Axon snapshots.',
    'May require permission to access selected folders.',
    'MVP must limit cleanup to clearly safe cache/temp locations and never delete personal files.',
    'planned',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_storage_cleanup_recommendation',
    'storage_cleanup_recommendation',
    'Storage cleanup recommendation',
    'storage_management',
    'Recommend storage cleanup opportunities without deleting files automatically.',
    1,
    NULL,
    'low',
    0,
    '["scan_storage_usage"]',
    0,
    0,
    'recommendation_only',
    'No rollback required because Axon only recommends; user performs or approves any actual cleanup separately.',
    'If a later action deletes files, that separate action must have its own capability and rollback classification.',
    'No elevated permission required for recommendation-only behaviour.',
    'Do not imply deletion has happened when only a recommendation was generated.',
    'planned',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
);

-- ---------------------------------------------------------------------------
-- Explicitly blocked MVP capabilities
-- ---------------------------------------------------------------------------

INSERT OR IGNORE INTO capability_registry (
    capability_id,
    capability_key,
    display_name,
    category,
    description,
    is_permitted_in_mvp,
    blocked_reason,
    risk_level,
    requires_admin,
    required_permissions_json,
    requires_gpu_telemetry,
    requires_thermal_data,
    reversibility_class,
    rollback_description,
    rollback_notes,
    permission_notes,
    safety_notes,
    implementation_status,
    added_in_version,
    created_at,
    updated_at
)
VALUES
(
    'cap_registry_modification_blocked',
    'registry_modification',
    'Registry modification',
    'blocked_system_change',
    'Modify Windows Registry keys or values.',
    0,
    'Explicitly disallowed by MVP safe action boundary.',
    'critical',
    1,
    '["registry_write","admin_possible"]',
    0,
    0,
    'blocked',
    'Blocked in MVP. No rollback is promised because the action must not be executed.',
    'Registry changes can be difficult to reverse safely and are out of scope.',
    'Often requires elevated permissions and can destabilise Windows or applications.',
    'Explicitly disallowed by MVP safe action boundary.',
    'blocked',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_driver_modification_blocked',
    'driver_modification',
    'Driver modification',
    'blocked_system_change',
    'Install, remove, update, disable, or alter device drivers.',
    0,
    'Explicitly disallowed by MVP safe action boundary.',
    'critical',
    1,
    '["driver_management","admin_required"]',
    0,
    0,
    'blocked',
    'Blocked in MVP. No rollback is promised because the action must not be executed.',
    'Driver operations can destabilise hardware, OS, games, anti-cheat, or security tooling.',
    'Requires elevated permissions and can cause device or OS instability.',
    'Explicitly disallowed by MVP safe action boundary.',
    'blocked',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_bios_firmware_interaction_blocked',
    'bios_firmware_interaction',
    'BIOS/firmware interaction',
    'blocked_system_change',
    'Read, write, modify, update, or control BIOS/UEFI/firmware settings.',
    0,
    'Explicitly disallowed by MVP safe action boundary.',
    'critical',
    1,
    '["firmware_access","admin_required","vendor_specific_tooling"]',
    0,
    0,
    'blocked',
    'Blocked in MVP. No rollback is promised because the action must not be executed.',
    'Firmware changes are outside Axon MVP trust and rollback boundaries.',
    'Firmware interaction is high-risk and vendor-specific.',
    'Explicitly disallowed by MVP safe action boundary.',
    'blocked',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_overclocking_blocked',
    'overclocking',
    'Overclocking',
    'blocked_performance_change',
    'Increase CPU/GPU/RAM clocks, power limits, or voltage-related performance limits.',
    0,
    'Explicitly disallowed by MVP safe action boundary.',
    'critical',
    1,
    '["hardware_control","admin_possible","vendor_specific_tooling"]',
    1,
    1,
    'blocked',
    'Blocked in MVP. No rollback is promised because the action must not be executed.',
    'Overclocking is specifically excluded from MVP to protect trust and hardware safety.',
    'Can cause crashes, overheating, warranty issues, or hardware instability.',
    'Explicitly disallowed by MVP safe action boundary.',
    'blocked',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_undervolting_blocked',
    'undervolting',
    'Undervolting',
    'blocked_performance_change',
    'Reduce CPU/GPU voltage or alter voltage curves.',
    0,
    'Explicitly disallowed by MVP safe action boundary.',
    'critical',
    1,
    '["hardware_control","admin_possible","vendor_specific_tooling"]',
    1,
    1,
    'blocked',
    'Blocked in MVP. No rollback is promised because the action must not be executed.',
    'Undervolting is vendor-specific and can cause instability despite appearing less risky than overclocking.',
    'Can cause instability and is vendor/tool specific.',
    'Explicitly disallowed by MVP safe action boundary.',
    'blocked',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_permanent_os_configuration_change_blocked',
    'permanent_os_configuration_change',
    'Permanent OS configuration change',
    'blocked_system_change',
    'Make persistent Windows configuration changes outside Axon-controlled reversible actions.',
    0,
    'Explicitly disallowed by MVP safe action boundary.',
    'critical',
    1,
    '["system_configuration_write","admin_possible"]',
    0,
    0,
    'blocked',
    'Blocked in MVP. No rollback is promised because the action must not be executed.',
    'MVP only permits tightly scoped app-controlled reversible changes.',
    'May have broad, unclear, or hard-to-reverse side effects.',
    'Explicitly disallowed by MVP safe action boundary.',
    'blocked',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
),
(
    'cap_security_policy_change_blocked',
    'security_policy_change',
    'Security policy change',
    'blocked_security_change',
    'Change firewall, antivirus, Defender, UAC, account, permissions, or security policy settings.',
    0,
    'Explicitly disallowed by MVP safe action boundary.',
    'critical',
    1,
    '["security_policy_write","admin_required"]',
    0,
    0,
    'blocked',
    'Blocked in MVP. No rollback is promised because the action must not be executed.',
    'Security policy changes would undermine trust and may create legal/support risk.',
    'Security changes create unacceptable trust and safety risk for MVP.',
    'Explicitly disallowed by MVP safe action boundary.',
    'blocked',
    '0.2',
    '2026-06-07T00:00:00Z',
    '2026-06-07T00:00:00Z'
);
